// <auto-generated />
using System;
using FamilyFlow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyFlow.Data.Migrations
{
    [DbContext(typeof(FamilyFlowDbContext))]
    [Migration("20260407095008_SeedTasksAndEvents")]
    partial class SeedTasksAndEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FamilyFlow.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "38bbdf9b-b4a7-489d-b6a4-c66728a23e00",
                            Email = "mother@familyflow.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MOTHER@FAMILYFLOW.COM",
                            NormalizedUserName = "MOTHER@FAMILYFLOW.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBfZF7D0lyB1bFKMJ/Aal4aX13OCVHeLjSx/Vbn1aBhzFIxW+CxjFt/sm/yimMHPnA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "94f76c6f-cb60-44a7-b1e7-20481abad09a",
                            TwoFactorEnabled = false,
                            UserName = "mother@familyflow.com"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "13ff91cd-a1da-4185-ae71-f6f4e43f38ac",
                            Email = "father@familyflow.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "FATHER@FAMILYFLOW.COM",
                            NormalizedUserName = "FATHER@FAMILYFLOW.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEM/kku3fZOC1Se6BirPvUndJjCjFkkh03OMzw2WyDUiqfopyh8cLyPJcbFkNVwwGA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "75d413ed-6e90-4385-ad53-abc08b5f31d8",
                            TwoFactorEnabled = false,
                            UserName = "father@familyflow.com"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "37aa2bda-ebd0-46c0-8c3b-4f1b704d70da",
                            Email = "son@familyflow.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SON@FAMILYFLOW.COM",
                            NormalizedUserName = "SON@FAMILYFLOW.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIxSGLIuJpbG7dCNoC4aRpUEk82ZHqdntlTKvPIkcVe9GlN7DrppIF3WW2xFJL7R8g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cee10e2f-2b41-4fbd-a7fd-142d784a58c8",
                            TwoFactorEnabled = false,
                            UserName = "son@familyflow.com"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e0532194-5935-4d8f-a8a2-8c34ded56416",
                            Email = "daughter@familyflow.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DAUGHTER@FAMILYFLOW.COM",
                            NormalizedUserName = "DAUGHTER@FAMILYFLOW.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEI3/yCNW1QkLrOVdiQ+jfQUzeKBC4h5+9/rKhP9dn1wycBsBh4Tu7vHMAhqvPlzASg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "db73695c-e32f-42e0-bc82-80d8b2ca45e4",
                            TwoFactorEnabled = false,
                            UserName = "daughter@familyflow.com"
                        });
                });

            modelBuilder.Entity("FamilyFlow.Data.Models.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Families");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Name = "Anderson",
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("FamilyFlow.Data.Models.FamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FamilyId")
                        .HasColumnType("int");

                    b.Property<Guid?>("LinkedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("LinkedUserId")
                        .IsUnique()
                        .HasFilter("[LinkedUserId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("FamilyMembers");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Age = 40,
                            FamilyId = 10,
                            LinkedUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Alice",
                            Role = 0,
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = 12,
                            Age = 42,
                            FamilyId = 10,
                            LinkedUserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Bob",
                            Role = 1,
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = 13,
                            Age = 6,
                            FamilyId = 10,
                            Name = "Charlie",
                            Role = 2,
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = 14,
                            Age = 10,
                            FamilyId = 10,
                            LinkedUserId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "Daisy",
                            Role = 3,
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = 15,
                            Age = 56,
                            FamilyId = 10,
                            Name = "Elise",
                            Role = 4,
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("FamilyFlow.Data.Models.HouseTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FamilyMemberId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FamilyMemberId");

                    b.ToTable("HouseTasks");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Description = "Wipe down counters and mop the floor",
                            DueDate = new DateTime(2026, 4, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            FamilyMemberId = 11,
                            IsCompleted = false,
                            Title = "Clean the kitchen"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Mow the front and back yard",
                            DueDate = new DateTime(2026, 4, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            FamilyMemberId = 12,
                            IsCompleted = false,
                            Title = "Mow the lawn"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Collect all trash and recycling and take to curb",
                            DueDate = new DateTime(2026, 4, 11, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            FamilyMemberId = 13,
                            IsCompleted = false,
                            Title = "Take out the trash"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Clean the exterior and interior of the car",
                            DueDate = new DateTime(2026, 4, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            FamilyMemberId = 12,
                            IsCompleted = false,
                            Title = "Wash the car"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sort and declutter items in the garage",
                            DueDate = new DateTime(2026, 4, 17, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FamilyMemberId = 12,
                            IsCompleted = false,
                            Title = "Organize the garage"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Buy groceries for the week",
                            DueDate = new DateTime(2026, 4, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FamilyMemberId = 11,
                            IsCompleted = false,
                            Title = "Grocery shopping"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Wash and fold clothes",
                            DueDate = new DateTime(2026, 4, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FamilyMemberId = 14,
                            IsCompleted = false,
                            Title = "Laundry"
                        });
                });

            modelBuilder.Entity("FamilyFlow.Data.Models.ScheduleEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccompanyingAdultId")
                        .HasColumnType("int");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AccompanyingAdultId");

                    b.ToTable("ScheduleEvents");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            AccompanyingAdultId = 11,
                            CreatorId = 11,
                            EndTime = new DateTime(2026, 4, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 4, 12, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Morning Walk"
                        },
                        new
                        {
                            Id = 8,
                            CreatorId = 12,
                            EndTime = new DateTime(2026, 4, 13, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 4, 13, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Family Meeting"
                        },
                        new
                        {
                            Id = 9,
                            AccompanyingAdultId = 12,
                            CreatorId = 13,
                            EndTime = new DateTime(2026, 4, 14, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 4, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Birthday Party"
                        },
                        new
                        {
                            Id = 10,
                            AccompanyingAdultId = 11,
                            CreatorId = 14,
                            EndTime = new DateTime(2026, 4, 15, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 4, 15, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Doctor Apointment"
                        });
                });

            modelBuilder.Entity("FamilyFlow.Data.Models.ScheduleEventParticipant", b =>
                {
                    b.Property<int>("ScheduleEventId")
                        .HasColumnType("int");

                    b.Property<int>("FamilyMemberId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleEventId", "FamilyMemberId");

                    b.HasIndex("FamilyMemberId");

                    b.ToTable("ScheduleEventParticipants");

                    b.HasData(
                        new
                        {
                            ScheduleEventId = 8,
                            FamilyMemberId = 12
                        },
                        new
                        {
                            ScheduleEventId = 8,
                            FamilyMemberId = 13
                        },
                        new
                        {
                            ScheduleEventId = 8,
                            FamilyMemberId = 14
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FamilyFlow.Data.Models.Family", b =>
                {
                    b.HasOne("FamilyFlow.Data.Models.ApplicationUser", "User")
                        .WithOne("Family")
                        .HasForeignKey("FamilyFlow.Data.Models.Family", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyFlow.Data.Models.FamilyMember", b =>
                {
                    b.HasOne("FamilyFlow.Data.Models.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyFlow.Data.Models.ApplicationUser", "LinkedUser")
                        .WithOne("LinkedFamilyMember")
                        .HasForeignKey("FamilyFlow.Data.Models.FamilyMember", "LinkedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyFlow.Data.Models.ApplicationUser", "User")
                        .WithMany("UserFamilyMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("LinkedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyFlow.Data.Models.HouseTask", b =>
                {
                    b.HasOne("FamilyFlow.Data.Models.FamilyMember", "FamilyMemberHouseTasks")
                        .WithMany("HouseTasks")
                        .HasForeignKey("FamilyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyMemberHouseTasks");
                });

            modelBuilder.Entity("FamilyFlow.Data.Models.ScheduleEvent", b =>
                {
                    b.HasOne("FamilyFlow.Data.Models.FamilyMember", "AccompanyingAdult")
                        .WithMany("AccompanyEvents")
                        .HasForeignKey("AccompanyingAdultId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AccompanyingAdult");
                });

            modelBuilder.Entity("FamilyFlow.Data.Models.ScheduleEventParticipant", b =>
                {
                    b.HasOne("FamilyFlow.Data.Models.FamilyMember", "FamilyMember")
                        .WithMany("EventParticipations")
                        .HasForeignKey("FamilyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyFlow.Data.Models.ScheduleEvent", "ScheduleEvent")
                        .WithMany("Participants")
                        .HasForeignKey("ScheduleEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyMember");

                    b.Navigation("ScheduleEvent");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FamilyFlow.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FamilyFlow.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyFlow.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FamilyFlow.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyFlow.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Family");

                    b.Navigation("LinkedFamilyMember");

                    b.Navigation("UserFamilyMembers");
                });

            modelBuilder.Entity("FamilyFlow.Data.Models.Family", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("FamilyFlow.Data.Models.FamilyMember", b =>
                {
                    b.Navigation("AccompanyEvents");

                    b.Navigation("EventParticipations");

                    b.Navigation("HouseTasks");
                });

            modelBuilder.Entity("FamilyFlow.Data.Models.ScheduleEvent", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
